// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbML5DGaioT7CON5tBdiodVtW0R3jeVF0',
    appId: '1:856538507392:web:832b1000ae0fcd417dde65',
    messagingSenderId: '856538507392',
    projectId: 'databasegtr001',
    authDomain: 'databasegtr001.firebaseapp.com',
    storageBucket: 'databasegtr001.firebasestorage.app',
    measurementId: 'G-8VMZBWTJTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_q8iTdmYOrXZhupaGKKhlCNoKI2B-cc',
    appId: '1:856538507392:android:6f47ef2df9b6ee427dde65',
    messagingSenderId: '856538507392',
    projectId: 'databasegtr001',
    storageBucket: 'databasegtr001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWWheFUD1OOG2hslThbvNdwvSasx2wjYE',
    appId: '1:856538507392:ios:52824d39024dc82d7dde65',
    messagingSenderId: '856538507392',
    projectId: 'databasegtr001',
    storageBucket: 'databasegtr001.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWWheFUD1OOG2hslThbvNdwvSasx2wjYE',
    appId: '1:856538507392:ios:52824d39024dc82d7dde65',
    messagingSenderId: '856538507392',
    projectId: 'databasegtr001',
    storageBucket: 'databasegtr001.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbML5DGaioT7CON5tBdiodVtW0R3jeVF0',
    appId: '1:856538507392:web:5c2d2ad4909e760b7dde65',
    messagingSenderId: '856538507392',
    projectId: 'databasegtr001',
    authDomain: 'databasegtr001.firebaseapp.com',
    storageBucket: 'databasegtr001.firebasestorage.app',
    measurementId: 'G-CVV7QDZGG1',
  );
}
