import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:project1/add_page.dart';
import 'package:project1/firebase_options.dart';
import 'package:project1/inventory_page.dart';
import 'package:project1/main.dart';
import 'package:project1/scan_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options:
        DefaultFirebaseOptions.currentPlatform, // Generated by FlutterFire CLI
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(colorScheme: .fromSeed(seedColor: Colors.deepPurple)),
      home: const ProfilePage(title: 'Profile'),
    );
  }
}

class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key, required this.title});
  final String title;

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  bool isEditing = false;
  bool isLoading = true;

  // Controllers
  final nameController = TextEditingController();
  final genderController = TextEditingController();
  final idController = TextEditingController();
  final departmentController = TextEditingController();
  final phoneController = TextEditingController();
  final emailController = TextEditingController();

  // Replace this with the actual logged-in user's ID
  final String userId = "user_123";

  @override
  void initState() {
    super.initState();
    fetchUserData(); // 2. Fetch data when page loads
  }

  // --- FIREBASE: GET DATA ---
  Future<void> fetchUserData() async {
    try {
      DocumentSnapshot doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(userId)
          .get();

      if (doc.exists) {
        Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
        setState(() {
          nameController.text = data['name'] ?? '';
          genderController.text = data['gender'] ?? '';
          idController.text = data['employeeId'] ?? '';
          departmentController.text = data['department'] ?? '';
          phoneController.text = data['phone'] ?? '';
          emailController.text = data['email'] ?? '';
          isLoading = false;
        });
      } else {
        setState(() => isLoading = false);
      }
    } catch (e) {
      print("Error fetching user: $e");
      setState(() => isLoading = false);
    }
  }

  // --- FIREBASE: SAVE DATA ---
  Future<void> saveUserData() async {
    try {
      await FirebaseFirestore.instance.collection('users').doc(userId).set({
        'name': nameController.text,
        'gender': genderController.text,
        'employeeId': idController.text,
        'department': departmentController.text,
        'phone': phoneController.text,
        'email': emailController.text,
        'updatedAt': Timestamp.now(),
      }, SetOptions(merge: true));

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Profile updated in Firebase")),
      );
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Failed to update: $e")));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.white,
        centerTitle: true,
        title: const Text("Profile", style: TextStyle(color: Colors.black)),
      ),
      body: isLoading
          ? const Center(
              child: CircularProgressIndicator(),
            ) // Show loader while fetching
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  // Profile info
                  CircleAvatar(
                    radius: 50,
                    backgroundColor: Colors.grey.shade300,
                    child: const Icon(
                      Icons.person,
                      size: 50,
                      color: Colors.white,
                    ),
                  ),

                  const SizedBox(height: 24),
                  Row(
                    children: [
                      Expanded(child: buildField("Full Name", nameController)),
                      const SizedBox(width: 12),
                      Expanded(child: buildField("Gender", genderController)),
                    ],
                  ),
                  const SizedBox(height: 12),
                  buildField("ID", idController),
                  const SizedBox(height: 12),
                  buildField("Department", departmentController),
                  const SizedBox(height: 12),
                  buildField("Phone Number", phoneController),
                  const SizedBox(height: 12),
                  buildField("E-Mail", emailController),
                  const SizedBox(height: 24),

                  ElevatedButton(
                    onPressed: () {
                      if (isEditing) {
                        saveUserData(); // 3. Trigger Save to Firebase
                      }
                      setState(() {
                        isEditing = !isEditing;
                      });
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.black,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 32,
                        vertical: 14,
                      ),
                    ),
                    child: Text(isEditing ? "Save" : "Update"),
                  ),
                ],
              ),
            ),
      bottomNavigationBar: BottomAppBar(
        height: 84,
        color: Colors.white,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            Column(
              children: [
                IconButton(
                  onPressed: () {
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(
                        builder: (context) => MyHomePage(title: 'Scan Barcode'),
                      ),
                    );
                  },
                  icon: Icon(Icons.home_outlined),
                ),
                Text('Home'),
              ],
            ),
            Column(
              children: [
                IconButton(
                  onPressed: () {
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(
                        builder: (context) => InventoryPage(title: 'Inventory'),
                      ),
                    );
                  },
                  icon: Icon(Icons.inventory),
                ),
                Text('Inventory'),
              ],
            ),
            Column(
              children: [
                IconButton(
                  onPressed: () {
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(
                        builder: (context) => AddPage(title: 'Add'),
                      ),
                    );
                  },
                  icon: Icon(Icons.add_circle_outline),
                ),
                Text('Add'),
              ],
            ),
            Column(
              children: [
                IconButton(
                  onPressed: () {
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(
                        builder: (context) => ScanPage(title: 'Scan Barcode'),
                      ),
                    );
                  },
                  icon: Icon(Icons.qr_code_scanner_outlined),
                ),
                Text('Scan'),
              ],
            ),
            Column(
              children: [
                IconButton(onPressed: () {}, icon: Icon(Icons.person_outlined)),
                Text('Profile'),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget buildField(String label, TextEditingController controller) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(fontWeight: FontWeight.w600)),
        const SizedBox(height: 6),
        TextField(
          controller: controller,
          enabled: isEditing,
          decoration: InputDecoration(
            filled: true,
            fillColor: isEditing ? Colors.grey.shade100 : Colors.grey.shade200,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
          ),
        ),
      ],
    );
  }
}
